name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+' 

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main

  release:
    needs: build
    runs-on: ubuntu-22.04

    env:
      Solution_Path: ".\\KSP Ukrainian Localization.sln"

    steps:
    - name: Parse and Validate Version from Tag
      id: parse_version
      run: |
        TAG=${{ github.ref_name }}
        echo "Processing tag: $TAG"

        if [[ $TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(\.([0-9]+))?$ ]]; then
          MAJOR=${BASH_REMATCH[1]}
          MINOR=${BASH_REMATCH[2]}
          PATCH=${BASH_REMATCH[3]}
          
          # The build number is optional, so check if the 5th group exists
          if [[ -n "${BASH_REMATCH[5]}" ]]; then
            BUILD=${BASH_REMATCH[5]}
          else
            echo "Build number not found in tag, defaulting to 0."
            BUILD=0
          fi

          VERSION="$MAJOR.$MINOR.$PATCH.$BUILD"
          echo "Successfully parsed version: $VERSION"
          
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=${VERSION}" >> "$GITHUB_ENV"
        else
          echo "::error::Tag format is invalid. Expected vMAJOR.MINOR.PATCH or vMAJOR.MINOR.PATCH.BUILD"
          exit 1
        fi

      uses: KSPModdingLibs/KSPBuildTools/.github/workflows/create-release.yml@main
      with:
        version-string: ${{ env.RELEASE_VERSION }}

